/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        'brand-base': 'var(--color-brand-base)',
        'brand-icon': 'var(--color-brand-icon)',
        'brand-text': 'var(--color-brand-text)',
        'accent-base': 'var(--color-accent-base)',
        'accent-subtle': 'var(--color-accent-subtle)',
        'neutral-base': 'var(--color-neutral-base)',
        'neutral-muted': 'var(--color-neutral-muted)',
        'neutral-inverse-muted': 'var(--color-neutral-inverse-muted)',
        'neutral-inverse-icon': 'var(--color-neutral-inverse-icon)',
        'semantic-error': 'var(--color-semantic-error)',
        'text-base': 'var(--color-text-base)',
        'text-muted': 'var(--color-text-muted)',
        'surface-error': 'var(--color-surface-error)',
        'sidebar-bg': 'var(--color-sidebar-bg)',
        // Extended palette
        'red-base': 'var(--color-red-base)',
        'red-light': 'var(--color-red-light)',
        'green-base': 'var(--color-green-base)',
        'green-light': 'var(--color-green-light)',
        'yellow-base': 'var(--color-yellow-base)',
        'yellow-light': 'var(--color-yellow-light)',
        'blue-base': 'var(--color-blue-base)',
        'blue-light': 'var(--color-blue-light)',
        'purple-base': 'var(--color-purple-base)',
        'purple-light': 'var(--color-purple-light)',
      },
      borderRadius: {
        'sm': 'var(--radius-sm)',
        'md': 'var(--radius-md)',
        'lg': 'var(--radius-lg)',
      },
      boxShadow: {
        'sm': 'var(--shadow-sm)',
        'md': 'var(--shadow-md)',
        'lg': 'var(--shadow-lg)',
        'xl': 'var(--shadow-xl)',
      },
      spacing: {
        'xs': 'var(--spacing-xs)',
        'sm': 'var(--spacing-sm)',
        'md': 'var(--spacing-md)',
        'lg': 'var(--spacing-lg)',
        'xl': 'var(--spacing-xl)',
        '2xl': 'var(--spacing-2xl)',
      },
    },
  },
  plugins: [],
};
